### ISSUE TITLE
is this still active?

### ISSUE THREAD

**Issue by pvinis** [lipidity/ledgible#2]
i cant make it run.

**Comment by fredguth** [comment]
also, demo isn't working

**Comment by lipidity** [comment]
The demo is up now.

"I can't make it run" doesn't provide much information for anybody to help. Please provide more details. What have you tried, etc?

**Comment by fredguth** [comment]
Hi @lipidity 
I tried to login the demo with user/password = demo/demo
But got an Internal Server Error.
I clicked on the link in the Github readme.  Is it elsewhere?

**Comment by lipidity** [comment]
@fredguth My apologies for the delayed reply (I was expecting github to notify me of a reply, so didn't check back). I have recently updated the server to use letsencrypt. Please try again at the same URL.
